### ISSUE TITLE
Business Application Studio Destination support

### ISSUE THREAD

**Issue by JanWerder** [mauriciolauffer/ui5-deployer#29]
Hello,

Thanks for creating tool, it's working great for me locally, but I'm having problems using it from the Business Application Studio. I've installed and configured it, as I would locally, but the "URL" parameter for deploying to a SAP Netweaver system doesn't work the same.

Since backend systems are exposed to the SAP Cloud via the Cloud Connector, I can't use the direct URL, but would have to use a "destination", I assume. But neither the direct URL nor the Destination works.

The relevant part of the ui5.yaml:
```customConfiguration:
  deployer:
    type: sap-netweaver
    sourcePath: dist/
    connection:
      url: http://internal.ide:443
      # proxy: https://my.proxy.com:43000
      strictSSL: false
      SSLCertificatePath: root.cer
```
The terminal output
```> ui5-deployer deploy

info deployer:deployer Deploying project MyApp
info deployer:deployer to SAP Netweaver
info deployer:deployer application MyApp Connecting to https://internal.url:44300
ERR! deployer:deployer RequestError: Cannot read property 'statusCode' of undefined
ERR! deployer:deployer     at Request._error (/home/user/projects/myapp/node_modules/ui5-deployer/node_modules/got/dist/source/core/index.js:1188:21)
ERR! deployer:deployer     at /home/user/projects/myapp/node_modules/ui5-deployer/node_modules/got/dist/source/core/index.js:1270:23
ERR! deployer:deployer     at AdtClient._responseError (/home/user/projects/myapp/node_modules/ui5-deployer/lib/types/sap-netweaver/AdtClient.js:455:32)
ERR! deployer:deployer     at reqOptions.hooks.beforeError (/home/user/projects/myapp/node_modules/ui5-deployer/lib/types/sap-netweaver/AdtClient.js:430:18)
ERR! deployer:deployer     at Request._error (/home/user/projects/myapp/node_modules/ui5-deployer/node_modules/got/dist/source/core/index.js:1184:31)
ERR! deployer:deployer     at /home/user/projects/myapp/node_modules/ui5-deployer/node_modules/got/dist/source/core/index.js:1270:23
ERR! deployer:deployer     at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERR! deployer:deployer  RequestError: Cannot read property 'statusCode' of undefined
ERR! deployer:deployer     at Request._error (/home/user/projects/myapp/node_modules/ui5-deployer/node_modules/got/dist/source/core/index.js:1188:21)
ERR! deployer:deployer     at /home/user/projects/myapp/node_modules/ui5-deployer/node_modules/got/dist/source/core/index.js:1270:23
ERR! deployer:deployer     at AdtClient._responseError (/home/user/projects/myapp/node_modules/ui5-deployer/lib/types/sap-netweaver/AdtClient.js:455:32)
ERR! deployer:deployer     at reqOptions.hooks.beforeError (/home/user/projects/myapp/node_modules/ui5-deployer/lib/types/sap-netweaver/AdtClient.js:430:18)
ERR! deployer:deployer     at Request._error (/home/user/projects/myapp/node_modules/ui5-deployer/node_modules/got/dist/source/core/index.js:1184:31)
ERR! deployer:deployer     at /home/user/projects/myapp/node_modules/ui5-deployer/node_modules/got/dist/source/core/index.js:1270:23
ERR! deployer:deployer     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
ERR! deployer:deployer   code: undefined,
ERR! deployer:deployer   timings: {
ERR! deployer:deployer     start: 1622123480932,
ERR! deployer:deployer     socket: 1622123480934,
ERR! deployer:deployer     lookup: 1622123480990,
ERR! deployer:deployer     connect: undefined,
ERR! deployer:deployer     secureConnect: undefined,
ERR! deployer:deployer     upload: undefined,
ERR! deployer:deployer     response: undefined,
ERR! deployer:deployer     end: undefined,
ERR! deployer:deployer     error: 1622123480990,
ERR! deployer:deployer     abort: undefined,
ERR! deployer:deployer     phases: {
ERR! deployer:deployer       wait: 2,
ERR! deployer:deployer       dns: 56,
ERR! deployer:deployer       tcp: undefined,
ERR! deployer:deployer       tls: undefined,
ERR! deployer:deployer       request: undefined,
ERR! deployer:deployer       firstByte: undefined,
ERR! deployer:deployer       download: undefined,
ERR! deployer:deployer       total: 58
ERR! deployer:deployer     }
ERR! deployer:deployer   }
ERR! deployer:deployer }
ERR! deployer:deployer Deploy failed in 119 ms

⚠️  Process Failed With Error

Error Message:
Cannot read property 'statusCode' of undefined

For details, execute the same command again with an additional '--verbose' parameter
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myapp@0.0.1 deploy: `ui5-deployer deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myapp@0.0.1 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-05-27T13_51_21_016Z-debug.log
```
(let's assume internal.url is an internal URL or a Destination)

I hope I've described the problem good enough, if not, don't hesitate to ask.
What could I do to deploy from the BAS?

Best Regards,
Jan

**Comment by mauriciolauffer** [comment]
Sorry, but this is not supported at this moment as you'd need to inform the destination and the tool'd have to use it rather than the `connection.url`.

**Comment by mauriciolauffer** [comment]
I'll add it to my to-do list and implement whenever I find some time  =)
